language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=x86

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-x86-android-23
script:
  - cd scripts
  - chmod +x ./testAutoCommit.sh
  - ./testAutoCommit.sh
after_success:
  - bash echo "Yata!"
